server:
  port: 8701

spring:
  application:
    name: feign-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/

feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix

logging:
  level:
    com.snowman.cloud.service.UserService: debug


#常用配置
#feign:
#  hystrix:
#    enabled: true #在Feign中开启Hystrix
#  compression:
#    request:
#      enabled: false #是否对请求进行GZIP压缩
#      mime-types: text/xml,application/xml,application/json #指定压缩的请求数据类型
#      min-request-size: 2048 #超过该大小的请求会被压缩
#    response:
#      enabled: false #是否对响应进行GZIP压缩
#logging:
#  level: #修改日志级别
#    com.snowman.cloud.service.UserService: debug


#在Feign中配置Ribbon可以直接使用Ribbon的配置
#在Feign中配置Hystrix可以直接使用Hystrix的配置




